config:
  aws:region: eu-central-1
  aws:profile: izimate
  izimate:domain: izimate.com
  # One-time setup (values stored encrypted after running):
  #   pulumi config set izimate:githubRepo your-org/izimate
  #   pulumi config set izimate:auth0Domain your-tenant.auth0.com
  #   pulumi config set izimate:auth0WebClientId <value>
  #   pulumi config set izimate:auth0Audience <value>
  #   pulumi config set --secret izimate:auth0WebClientSecret <value>
  #   pulumi config set --secret izimate:auth0Secret <value>
  #   pulumi config set --secret vercel:apiToken <value>

  izimate:githubRepo: bojidaryovchev/izimate
  izimate:auth0Domain: dev-jcya8ymq1mu144dn.eu.auth0.com
  izimate:auth0WebClientId: mXPWr7sLTwJ48AHmYkoxOuQEvth3nIoR
  izimate:auth0Audience: https://api.izimate.com
  izimate:auth0WebClientSecret:
    secure: v1:xpj7fYIBbTPVWolK:fpKBidgfBBBZrdNiHRsmVwfi1w/Yb60cKk/1qMIMjY2QjFT6MehMOEuDhW/mwv5wUXxab6k7IF9w9mtCe0HODAnMff99c10RVJZoNtalzRU=
  izimate:auth0Secret:
    secure: v1:JKTwNuLipVIo56+6:CfVt9BAttQXyZMJTQkyl5/41Ry5QED3QfxhGb9+GtFRJhceBv05MNgefrNmwYwqGSLfOets+2Pqm3ovpeTkire4Uc2PpzlvaJDK4V03rMeY=
  vercel:apiToken:
    secure: v1:y9o6CEd5iza3RYes:mONjboHtluhujwaFYdJTy+5O0+d1SJ5zKIgdoPCSyOwvyiiywknRAmzldcQXaW1ypFdZQNnSDt7FEYw21XsEhxh9oW9XZlY7yZCoVA==
  izimate:hostedZoneId: Z050857227WWERAOAPPFE
  izimate:databaseUrl:
    secure: v1:IVQTyjr9jsOWLiM/:vfCjdnL4T26RI9Jvh7VkCkWMHWIZN5cZ2fVbdbQ5ga+U2tnISUHWUQ2W3Bnn1qsjQvttzEGQRqkP1laexPbIpiuOpk9b4k5fyTPByrGyh7Wu1U2+dDz/omWu8n15hCrm337k+LZ28kisq5rGDmlEQhhjWukQ2F0SkRNv02HhqX0KisRLbhUxuHPlYt7pKDfIW35kwz0l9IhQaYbPrYdgDBG7abiFsHXb
  izimate:resendApiKey:
    secure: v1:BsuzJ5FTrhPJ0nfc:hLRTtF6/78Z1/VrBMjzhgdAGtp2wn+0KHMSe22RP0Y1fbzf+SU5i0NzeIyfCRgBsbP1lKg==
  izimate:stripeSecretKey:
    secure: v1:Rrmb+QOeh8qgJ+Fw:zXOrTKFBh5yz8dpFZlSalUkGxU5uMqTa3Zd4dWk+K/SbdG6NYL1m8/eJOwmSqFvbkjip4zCuTPtPK5ZoKuZTZCLPPmR87WOtdrep/2jBtwCZX2QwNTh50qcOPJ2SuK1kAyYmrOHhhs9PiRDVPb9UBxZJb7a1F2HP7Xja
  izimate:stripeWebhookSecret:
    secure: v1:wUeS9+mDwAhuwW2y:xFAfVgJrRtqrmgUMEZG0ev8Q7bnFDpbA04i4zRMNbIwY/zHhcNr8Pswd0W/NECxYTEzWDaZA
  izimate:r2AccountId:
    secure: v1:RgUIExxC0dOOCljm:iVv0l9qpbUVoQE3r9RHRf13SAw48RwvvQrN7WBhpKy6Gibam3cSHTUpcsj3JoQSR
  izimate:r2AccessKeyId:
    secure: v1:Ut9vDdntV95Uwx57:WsgjF+DPtT4+h1RxNXtt9V83V0M54Zuo9Jjouxu7lv9Ifq0vd3U/ueGkSP8IeIAV
  izimate:r2SecretAccessKey:
    secure: v1:4eoSbJf73B5Rw0LQ:IZV3zEYh6shg7LefSOr/XCex0J49PkS8L295KHHUpEFsBUMUd2Uk3fDecHaad7on0pKrgNB2NAnsKQSHJbgilWN9foNihsPaKpZ8Pe7HkCw=
  izimate:r2Bucket: izimate-uploads
encryptionsalt: v1:qsM9zeE+J6Q=:v1:iryQ3xLeTtGOs7Tx:KOxrptEcAIf/tGwHmvw4fWCnyOi0ng==
